### ISSUE TITLE
how to create a topology file

### ISSUE THREAD

**Issue by farmacyst99** [marrink-lab/martini-forcefields#6]
I am a student & I am using the martini 3 parameters for the lipidome tutorial that you have given on your website. I am unable to make a topology file for the dppc lipid. How do I make one? What should be the format of the topolgy file.

**Comment by ricalessandri** [comment]
Here's the topology for the current Martini 3 DPPC lipid model:
https://github.com/marrink-lab/martini-forcefields/blob/784591ebdc91d762ed4df986c4650546c938f776/martini_forcefields/regular/v3.0.0/gmx_files/martini_v3.0.0_phospholipids_v1.itp#L506-L562
